version: '3.8'

services:
  vite-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vite-react-app
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - vite-network

networks:
  vite-network:
    driver: bridge